/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * Media type of the attachment.
 */
export enum AttachmentMimeType {
    ImagePng = "image/png",
    ImageJpg = "image/jpg",
    ImageJpeg = "image/jpeg",
    ApplicationPdf = "application/pdf",
}

export class Attachment extends SpeakeasyBase {
    /**
     * The date-time the attachment was added.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "attachedAt" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    attachedAt: Date;

    /**
     * A file checksum is like a unique digital fingerprint that helps ensure a file hasn’t been tampered with during transfer or storage, providing data integrity and security assurance.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "checksum" })
    checksum?: string;

    /**
     * Media type of the attachment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "mimeType" })
    mimeType: AttachmentMimeType;

    /**
     * URL to download attachment
     */
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;
}
