/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * Type of wallet load
 */
export enum WalletLoadType {
    Card = "card",
    WireTransfer = "wireTransfer",
}

export class WalletLoad extends SpeakeasyBase {
    /**
     * Amount of the wallet load. Always in wallet currency.
     *
     * @remarks
     * Expressed in smallest units of the currency (e.g. cents for EUR and USD, but yen for JPY).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: number;

    /**
     * The date-time the wallet load got created in the system
     */
    @SpeakeasyMetadata()
    @Expose({ name: "createdAt" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    createdAt: Date;

    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "currency" })
    currency: string;

    /**
     * ID of wallet
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * Type of wallet load
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: WalletLoadType;
}
