/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { classToPlain, Expose, Type } from "class-transformer";

export class Errors extends SpeakeasyBase {
    /**
     * Readable error message that could be displayed in a UI
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code: string;

    /**
     * Further description provided to give wider context into the error
     */
    @SpeakeasyMetadata()
    @Expose({ name: "detail" })
    detail: string;

    /**
     * Optional: Known source of error such as missing or invalid field in a request
     */
    @SpeakeasyMetadata()
    @Expose({ name: "source" })
    source?: string;
}

export class ErrorT extends Error {
    @SpeakeasyMetadata({ elemType: Errors })
    @Expose({ name: "errors" })
    @Type(() => Errors)
    errors?: Errors[];

    constructor(err?: ErrorT) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "ErrorT";
        Object.setPrototypeOf(this, ErrorT.prototype);
    }
}
