/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetCostCentersSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    authorizationCodeFlow?: string;

    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    clientAuthFlow?: string;
}

export class GetCostCentersRequest extends SpeakeasyBase {
    /**
     * An array of cost center IDs
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=ids" })
    ids?: string[];

    /**
     * Page number
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page" })
    page?: number;

    /**
     * Page size
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=pageSize" })
    pageSize?: number;
}

export class GetCostCenters200ApplicationJSONData extends SpeakeasyBase {
    /**
     * Cost center co-owner ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "coOwners" })
    coOwners: string[];

    /**
     * Cost center ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * Name of cost center
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * Cost center owner ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "owner" })
    owner: string;
}

/**
 * OK
 */
export class GetCostCenters200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: GetCostCenters200ApplicationJSONData })
    @Expose({ name: "data" })
    @Type(() => GetCostCenters200ApplicationJSONData)
    data: GetCostCenters200ApplicationJSONData[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => shared.Pagination)
    meta: shared.Pagination;
}

export class GetCostCentersResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    getCostCenters200ApplicationJSONObject?: GetCostCenters200ApplicationJSON;
}
