/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetExpenseCategoriesSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    authorizationCodeFlow?: string;

    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    clientAuthFlow?: string;
}

export class GetExpenseCategoriesRequest extends SpeakeasyBase {
    /**
     * An array of expense category IDs
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=ids" })
    ids?: string[];

    /**
     * Page number
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page" })
    page?: number;

    /**
     * Page size
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=pageSize" })
    pageSize?: number;
}

export class GetExpenseCategories200ApplicationJSONDataCostCenters extends SpeakeasyBase {
    /**
     * Cost center ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * Name of cost center
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}

export class GetExpenseCategories200ApplicationJSONData extends SpeakeasyBase {
    /**
     * Array of cost centers
     */
    @SpeakeasyMetadata({ elemType: GetExpenseCategories200ApplicationJSONDataCostCenters })
    @Expose({ name: "costCenters" })
    @Type(() => GetExpenseCategories200ApplicationJSONDataCostCenters)
    costCenters: GetExpenseCategories200ApplicationJSONDataCostCenters[];

    /**
     * Expense category ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * Name of expense category
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}

/**
 * OK
 */
export class GetExpenseCategories200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: GetExpenseCategories200ApplicationJSONData })
    @Expose({ name: "data" })
    @Type(() => GetExpenseCategories200ApplicationJSONData)
    data?: GetExpenseCategories200ApplicationJSONData[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => shared.Pagination)
    meta?: shared.Pagination;
}

export class GetExpenseCategoriesResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    getExpenseCategories200ApplicationJSONObject?: GetExpenseCategories200ApplicationJSON;
}
