/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

/**
 * OAuth2 grant type: `client_credentials`
 */
export enum PostAccessTokenRequestBodyGrantType {
    ClientCredentials = "client_credentials",
}

export class PostAccessTokenRequestBody extends SpeakeasyBase {
    /**
     * OAuth2 grant type: `client_credentials`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "grant_type" })
    grantType?: PostAccessTokenRequestBodyGrantType;

    /**
     * Optional field to restrict the scope of the token. The default scope will match the scope defined in the front end when generating your API client id and secret.
     *
     * @remarks
     *
     * Space separated list of available scopes:
     * `bank-fee:read` `payable:read` `payable-attachment:read` `settlement:read` `wallet-load:read` `wallet-summary:read` `user:read` `supplier:read` `analytical-field:read`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope?: string;
}

export class PostAccessTokenRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: PostAccessTokenRequestBody;
}

/**
 * OK
 */
export class PostAccessToken200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "access_token" })
    accessToken: string;

    /**
     * `Bearer`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token_type" })
    tokenType: string;
}

export class PostAccessTokenResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    postAccessToken200ApplicationJSONObject?: PostAccessToken200ApplicationJSON;
}
